### PR TITLE
Phase 6 requirements

### PR DESCRIPTION
**Pull request by monitorjbl**
* Removing join date from blasts
* Adding google map
* Randomizing feed order

[Review on Reviewable](https://reviewable.io/reviews/cscobootcamp/referencerepo/18)

### CODE REVIEW

**Comment by segfly** [comment]
When the browser window size is smaller than about 1192px, the map wraps under the blast list. I did not see the map at first, and when I did I thought you decided not to put it side-by-side. I only noticed this was correct when I was about to send you my c9 preview and I opened it up full screen.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[app.css, line 83 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJvFWxcKyyKE0f5j1e)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/app.css#L83)):</sup>
I'm guessing this is the wrapping culprit. I'd have to dig back into CSS reference, but I'm thinking this probably needs to be max size. Probably need a min-size on the .body as well.

---

<sup>**[js/geo-service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJw9C5U9JIViu5P4jB)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/js/geo-service.js#L1)):</sup>
Did you end up having to create a lookup for these because of the geocoding rate limit?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by monitorjbl** [comment]
Ah, yeah. That's Bootstrap's grid layout at work...it'll change the max width of the container from 12 to 6 on smaller screens. Any idea what the smallest screen we should support will be? I can toss some media queries in to make it shrink nicely.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[app.css, line 83 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJvFWxcKyyKE0f5j1e)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/app.css#L83)):</sup>
Not sure if that'll work, I was seeing some strange behavior with the map if I didn't give it a specific size in pixels. I'll play with it a bit and see if I can get it to stretch/shrink better. I don't believe this is what causes the wrapping though, I believe that's just Bootstrap defaults kicking in.

---

<sup>**[js/geo-service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJw9C5U9JIViu5P4jB)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/js/geo-service.js#L1)):</sup>
You guessed it. 2.5k requests per day and 10 requests/sec...pretty limiting for a class of 40-50 people. I left the code in that will do it live, it just won't be able to load all points in a once.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by segfly** [comment]
Not really. I'd target somewhere between 800-1024 wide to allow for less-than-fullsize windows.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by segfly** [comment]
<sup>**[js/geo-service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJw9C5U9JIViu5P4jB)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/js/geo-service.js#L1)):</sup>
Makes sense.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by segfly** [comment]
<sup>**[js/geo-service.js, line 1 \[r1\]](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18#-JyJw9C5U9JIViu5P4jB)** ([raw file](https://github.com/cscobootcamp/referencerepo/blob/738de4c7e0d7a53cdad3fe282e03ee8e9f24f5ae/js/geo-service.js#L1)):</sup>
:shipit: 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by monitorjbl** [comment]
Found a technique to dynamically rescale the map window and I added medium/small classes to the split-column divs. It should stop wrapping around now unless you're on mobile.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by segfly** [comment]
Nice! :shipit: 

---

Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Comment by segfly** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/18)

**Pull request merged**
