### PR TITLE
Phase 7 requirements

### PR DESCRIPTION
**Pull request by monitorjbl**
adding scroll animation to blast list

improving layout to fit better with map

adding font for title

fixing css bug

using htps for google fonts

[Review on Reviewable](https://reviewable.io/reviews/cscobootcamp/referencerepo/22)

### CODE REVIEW

**Comment by monitorjbl** [comment]
Sorry for the delay, this has been done for a while. I meant to open the PR when I got back from Connecticut but I got wrapped up in some other stuff.

**Comment by monitorjbl** [comment]
The preview is available here: https://preview.c9.io/monitorjbl/referencerepo/app.html

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/22)

**Comment by segfly** [comment]
Hey, I think you misunderstood the requirements - or they weren't clear. The blasts were supposed to auto-rotate every 5 seconds, and only 3 should be shown at a time. The mockup shows that the manual buttons are removed.

I'm going to merge this anyway. Not much time to do anything about it, and it doesn't matter all that much.

Thanks!

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/22)

**Comment by monitorjbl** [comment]
Oh shoot. That shouldn't be too hard, I'll open a PR for it this weekend. If you have time to review and merge, great. If you don't, at least my inner completionist will be satisfied.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/22)

**Pull request merged**
