### PR TITLE
adding phase 4 requirements

### PR DESCRIPTION
**Pull request by monitorjbl**
hiding inactive users

adding user location info

adding highlighting to blast borders

[Review on Reviewable](https://reviewable.io/reviews/cscobootcamp/referencerepo/13)

### CODE REVIEW

**Comment by monitorjbl** [comment]
Did we get rid of the reviewable integration?

**Comment by segfly** [comment]
Wierd. Yeah, I wonder what happened to reviewable.

**Comment by segfly** [comment]
It shows up in reviewable, but it did not appear to put the badge on your PR for some reason. https://reviewable.io/reviews/cscobootcamp/referencerepo/13

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/13)

**Comment by segfly** [comment]
Great job!

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cscobootcamp/referencerepo/13)

**Pull request merged**
